{% set name = "cosapp_lab" %}
{% set version = "0.15.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 174699481597fd43a5ea6f179088b5f6fa54f83d0155909b11d0bd5fc4afda6a

build:
  noarch: python
  number: 0
  skip_compile_pyc:
    - '*/utils/templates/*.py'
  entry_points:
    - cosapp = cosapp_lab.main:cosapp
  script: {{ PYTHON }} -m pip install .  -vvv

requirements:

  host:
    - python >=3.6
    - pip
    - setuptools
    - jupyter-packaging

  run:
    - python >=3.6
    - cosapp >=0.11
    - ipywidgets >=7.6.3
    - pythonocc-core =7.4.0
    - click
    - requests
    - jupyter_client >=6.1
    - jupyter_server >=1.2
    - tornado >=6.1.0
    - jinja2
    - markdown
    - cookiecutter

test:
  imports:
    - cosapp_lab

about:
  home: https://gitlab.com/cosapp/cosapp_lab
  summary: Toolbox for managing and deploying CoSApp powered dashboards.
  description: |
    "# CosApp Lab - Toolbox for managing and deploying CoSApp powered dashboards.

    The primary goal of CoSApp Lab is to help users transform theirs existing CoSApp
    library into a interactive dashboard with almost no additional development or
    configuration."
  keywords: cosapp_lab
  dev_url: https://gitlab.com/cosapp/cosapp_lab
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - trungle-safran
