{% set name = "cosapp_lab" %}
{% set version = "1.0.0" %}
{% set pypi_version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ pypi_version }}.tar.gz
  sha256: cd6dca790f8d38cd7abdd6492af84863994c5be5793ea206c711a2088b9f232b

build:
  noarch: python
  number: 1
  skip_compile_pyc:
    - '*/utils/templates/*.py'
  entry_points:
    - cosapp = cosapp_lab.main:cosapp

requirements:

  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - jupyterlab >=4,<5
    - hatch-jupyter-builder
    - hatch-nodejs-version >=0.3.2

  run:
    - python >={{ python_min }}
    - cosapp >=0.13
    - ipywidgets >=8,<9
    - pythonocc-core >=7.6
    - click
    - requests
    - jupyter_client >=8
    - jupyter_server >=2
    - nb_conda_kernels
    - tornado >=6.1.0
    - jinja2
    - cookiecutter
    - markdown

test:
  requires:
    - python {{ python_min }}
  imports:
    - cosapp_lab

about:
  home: https://gitlab.com/cosapp/cosapp_lab
  summary: Toolbox for managing and deploying CoSApp powered dashboards.
  description: |
    "# CosApp Lab - Toolbox for managing and deploying CoSApp powered dashboards.

    The primary goal of CoSApp Lab is to help users transform theirs existing CoSApp
    library into a interactive dashboard with almost no additional development or
    configuration."
  keywords: cosapp_lab
  dev_url: https://gitlab.com/cosapp/cosapp_lab
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - elac-safran
