{% set name = "cosapp_lab" %}
{% set version = "0.16.0" %}
{% set pypi_version = "0.16.0-1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ pypi_version }}.tar.gz
  sha256: da3c4e8279f7795a1930ebdd5ba36f7cdc6d27d2c06313faec643fd89048f744

build:
  noarch: python
  number: 1
  skip_compile_pyc:
    - '*/utils/templates/*.py'
  entry_points:
    - cosapp = cosapp_lab.main:cosapp

requirements:

  host:
    - python >=3.8
    - pip
    - setuptools
    - jupyter-packaging

  run:
    - python >=3.8
    - cosapp >=0.13
    - ipywidgets >=7.6.3,<8
    - pythonocc-core >=7.4
    - click
    - requests
    - jupyter_client >=6.1
    - jupyter_server >=1.2
    - tornado >=6.1.0
    - jinja2
    - markdown
    - cookiecutter

test:
  imports:
    - cosapp_lab

about:
  home: https://gitlab.com/cosapp/cosapp_lab
  summary: Toolbox for managing and deploying CoSApp powered dashboards.
  description: |
    "# CosApp Lab - Toolbox for managing and deploying CoSApp powered dashboards.

    The primary goal of CoSApp Lab is to help users transform theirs existing CoSApp
    library into a interactive dashboard with almost no additional development or
    configuration."
  keywords: cosapp_lab
  dev_url: https://gitlab.com/cosapp/cosapp_lab
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - elac-safran
